# Site settings
name: midiDice
email: mididice@gmail.com
author: midiDice
url: http://localhost:4000/
resume_site: 
github: https://github.com/mididcie/
baseurl: ""
description: ""
meta_description: 
motto: midiDice
banner: 

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: mididice

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

