# Site settings
name: midiDICE blog
email: mididice@gmail.com
author: midiDICE
url: http://mididice.github.io/
resume_site: 
github: https://github.com/mididice/
baseurl: 
description: ""
meta_description: midiDICE team blog 
motto: midiDICE
banner: 

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: mididice

# Build settings
markdown: kramdown

# Custom settings
defaults:
  - scope:
      path: "assets"
    values:
      image: true
